### ISSUE TITLE
TODO - TEST

### ISSUE THREAD

**Issue by choewy** [choewy/alonerz-front-test#1]
- [ ] 사용자 차단 테스트
- [ ] 팔로잉 / 팔로워 / 차단 목록 테스트
- [ ] 그룹 댓글 테스트
- [ ] 소켓 테스트
